### PR TITLE
Supporting classpath for linkmove -> extractorsDir

### PR DESCRIPTION
**Pull request by vvertinskiy**
bootique-linkmove supports classpath for setting linkmove -> extractorsDir.
1. If linkmove -> extractorsDir contains prefix 'classpath:' then linkmove extractors will be loaded from classpath.
2. Classpath what is defined after 'classpath:' prefix is root class path of linkmove extractors
3. If linkmove -> extractorsDir DOES NOT contains prefix 'classpath:' then linkmove extractors will be loaded from directory what is defined in this setting (old behavior).

### CODE REVIEW

**Comment by vvertinskiy** [comment]
4. Setting 'linkmove -> extractorDirs' supports file-protocol (file://<path-to-directory>)

**Comment by andrus** [comment]
To be clear, this PR is in reference to #5

**Comment by andrus** [comment]
@vvertinskiy : looks good. A few suggestions:

1. Let's remove dependency on commons-lang StringUtils.
2. Anonymous ```ClasspathExtractorModelLoader``` subclass has a ```getRoot()``` method. Instead of dynamically calculating root, lets pre-calculate it and store in a final variable.

**Comment by vvertinskiy** [comment]
Andrus' suggestions have been applied in #6

**Comment by andrus** [comment]
@vvertinskiy  when reviewing the original PR I overlooked the fact that it is not using Bootique ```FolderResourceFactory``` (which was mentioned in #5 task description), so it reinvents the wheel quiet a bit. Another idea though - let's just implement the following task on LinkMove side: https://github.com/nhl/link-move/issues/101 . After that #5 will become trivial, based on FolderResourceFactory.

**Comment by andrus** [comment]
This feature has led to bigger refactoring (#5, #25, https://github.com/nhl/link-move/issues/133). Closing the PR, as it is no longer applicable.

**Pull request closed without merging**
